## Data Cleaning and Extraction

In [4]:
import pandas as pd

In [6]:
raw_data = pd.read_csv("owid-energy-data.csv")
print(raw_data.shape)

(21812, 129)

In [3]:
raw_data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [11]:
# Keep only data of countries
country_data = raw_data[raw_data['iso_code'].notna()]

16812

In [13]:
#Data of countries 
world_data = raw_data[raw_data['country'] == "World"]
print(len(world_data))

124

In [14]:
world_data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
21304,World,1900,NaN,1.627883e+09,3.503708e+12,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21305,World,1901,NaN,1.638648e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21306,World,1902,NaN,1.651840e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21307,World,1903,NaN,1.665704e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21308,World,1904,NaN,1.679753e+09,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
codes = pd.read_csv("owid-energy-codebook.csv")
codes = codes[["column","description"]]

                     column                                        description
0                   country                     Country - Geographic location.
1                      year                        Year - Year of observation.
2                  iso_code  ISO code - ISO 3166-1 alpha-3 three-letter cou...
3                population  Population - Population by country, available ...
4                       gdp  Gross domestic product (GDP) - This data is ad...
..                      ...                                                ...
124    wind_elec_per_capita  Electricity generation from wind power per per...
125        wind_electricity  Electricity generation from wind power - Measu...
126  wind_energy_per_capita  Wind power consumption per capita - Measured i...
127         wind_share_elec  Share of electricity generated by wind power -...
128       wind_share_energy  Share of primary energy consumption that comes...

[129 rows x 2 columns]